using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SpotifyClone.Playlists.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
public partial class Playlists_Replace_Property_IsAutoGenerated_With_Type : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "is_auto_generated",
            schema: "playlists",
            table: "playlists");

        migrationBuilder.AddColumn<int>(
            name: "type",
            schema: "playlists",
            table: "playlists",
            type: "integer",
            nullable: false,
            defaultValue: 0);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "type",
            schema: "playlists",
            table: "playlists");

        migrationBuilder.AddColumn<bool>(
            name: "is_auto_generated",
            schema: "playlists",
            table: "playlists",
            type: "boolean",
            nullable: false,
            defaultValue: false);
    }
}
