// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotifyClone.Streaming.Infrastructure.Persistence.Database;

#nullable disable

namespace SpotifyClone.Streaming.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StreamingAppDbContext))]
    [Migration("20260126112127_Streaming_Add_ImageAsset_Entity")]
    partial class Streaming_Add_ImageAsset_Entity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("streaming")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotifyClone.Streaming.Domain.Aggregates.AudioAssets.AudioAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("format");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.HasKey("Id");

                    b.ToTable("audio_assets", "streaming");
                });

            modelBuilder.Entity("SpotifyClone.Streaming.Domain.Aggregates.ImageAssets.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.HasKey("Id");

                    b.ToTable("image_assets", "streaming");
                });

            modelBuilder.Entity("SpotifyClone.Streaming.Domain.Aggregates.ImageAssets.ImageAsset", b =>
                {
                    b.OwnsOne("SpotifyClone.Shared.Kernel.ValueObjects.ImageMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ImageAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("metadata_file_type");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("metadata_height");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("metadata_size_in_bytes");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("metadata_width");

                            b1.HasKey("ImageAssetId");

                            b1.ToTable("image_assets", "streaming");

                            b1.WithOwner()
                                .HasForeignKey("ImageAssetId");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
