// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotifyClone.Streaming.Infrastructure.Persistence.Database;

#nullable disable

namespace SpotifyClone.Streaming.Infrastructure.Persistence.Migrations;

[DbContext(typeof(StreamingAppDbContext))]
partial class StreamingAppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("streaming")
            .HasAnnotation("ProductVersion", "10.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SpotifyClone.Streaming.Domain.Aggregates.AudioAssets.AudioAsset", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<TimeSpan>("Duration")
                    .HasColumnType("interval")
                    .HasColumnName("duration");

                b.Property<long>("FileSizeInBytes")
                    .HasColumnType("bigint")
                    .HasColumnName("file_size_in_bytes");

                b.Property<string>("Format")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("format");

                b.Property<bool>("IsReady")
                    .HasColumnType("boolean")
                    .HasColumnName("is_ready");

                b.HasKey("Id");

                b.ToTable("audio_assets", "streaming");
            });
#pragma warning restore 612, 618
    }
}
