using SpotifyClone.Shared.BuildingBlocks.Application.Errors;

namespace SpotifyClone.Playlists.Application.Errors;

public static class PlaylistErrors
{
    public static readonly Error InvalidMetadata = new(
        "Playlist.InvalidMetadata",
        "Playlist metadata is invalid.");

    public static readonly Error InvalidCover = new(
        "Playlist.InvalidCover",
        "Playlist cover is invalid.");

    public static readonly Error InvalidOwner = new(
        "Playlist.InvalidOwner",
        "The provided owner of the playlist if invalid.");

    public static readonly Error NotOwned = new(
        "Playlist.NotOwned",
        "Playlist is not owned by the current user.");

    public static readonly Error InvalidCollaborator = new(
        "Playlist.InvalidCollaborator",
        "The specified collaborator is invalid.");

    public static readonly Error InvalidTrack = new(
        "Playlist.InvalidTrack",
        "The specified track is invalid.");

    public static readonly Error IsNotUserGenerated = new(
        "Playlist.IsAutoGenerated",
        "This playlist was not generated by a user.");

    public static readonly Error UserNotLoggedIn = new(
        "Playlist.UserNotLoggedIn",
        "The user is not authenticated.");

    public static readonly Error NotFound = CommonErrors.NotFound(
        "Playlist", "Playlist");
}
