using SpotifyClone.Playlists.Application.Abstractions;

namespace SpotifyClone.Playlists.Application.Features.Playlists.Commands.Create;

public sealed record CreatePlaylistCommand(
    Guid? OwnerId = null,
    bool IsAutoGenerated = false,
    string? Name = null,
    string? Description = null)
    : IPlaylistsPersistentCommand<CreatePlaylistCommandResult>;
