using FluentValidation;

namespace SpotifyClone.Playlists.Application.Features.Playlists.Commands.Create;

public sealed class CreatePlaylistCommandValidator
    : AbstractValidator<CreatePlaylistCommand>
{
    public CreatePlaylistCommandValidator()
    {
        RuleFor(x => x.OwnerId)
            .NotEqual(Guid.Empty).WithMessage("Owner ID cannot be empty.");

        RuleFor(x => x.IsAutoGenerated)
            .NotNull().WithMessage("Is auto-generated flag is required.");
    }
}
