using SpotifyClone.Playlists.Application.Abstractions;
using SpotifyClone.Playlists.Application.Errors;
using SpotifyClone.Playlists.Domain.Aggregates.Playlists;
using SpotifyClone.Playlists.Domain.Aggregates.Playlists.ValueObjects;
using SpotifyClone.Shared.BuildingBlocks.Application.Abstractions.Commands;
using SpotifyClone.Shared.BuildingBlocks.Application.Abstractions.Primitives;
using SpotifyClone.Shared.BuildingBlocks.Application.Results;
using SpotifyClone.Shared.Kernel.IDs;

namespace SpotifyClone.Playlists.Application.Features.Playlists.Commands.Create;

internal sealed class CreatePlaylistCommandHandler(
    IPlaylistsUnitOfWork unit,
    ICurrentUser currentUser)
    : ICommandHandler<CreatePlaylistCommand, CreatePlaylistCommandResult>
{
    private readonly IPlaylistsUnitOfWork _unit = unit;
    private readonly ICurrentUser _currentUser = currentUser;

    public async Task<Result<CreatePlaylistCommandResult>> Handle(
        CreatePlaylistCommand request,
        CancellationToken cancellationToken)
    {
        Result<UserId> ownerId = GetOwner(request.OwnerId);
        if (ownerId.IsFailure)
        {
            return Result.Failure<CreatePlaylistCommandResult>(ownerId.Errors);
        }

        string name = await GetName(request.Name, ownerId.Value, cancellationToken);

        var playlist = Playlist.Create(
            PlaylistId.New(),
            name,
            request.Description,
            ownerId.Value,
            request.IsAutoGenerated);

        await _unit.Playlists.AddAsync(playlist, cancellationToken);

        return new CreatePlaylistCommandResult(playlist.Id.Value);
    }

    private Result<UserId> GetOwner(Guid? ownerId)
    {
        if (ownerId is null)
        {
            if (!_currentUser.IsAuthenticated)
            {
                return Result.Failure<UserId>(PlaylistErrors.InvalidOwner);
            }

            return UserId.From(_currentUser.Id);
        }

        return UserId.From(ownerId.Value);
    }

    private async Task<string> GetName(
        string? name,
        UserId ownerId,
        CancellationToken cancellationToken)
    {
        if (name is null)
        {
            IEnumerable<Playlist> playlists = await _unit.Playlists.GetAllByOwnerAsync(
                ownerId,
                cancellationToken);
            return $"My Playlist #{playlists.Count() + 1}";
        }
        return name;
    }
}
